version: '3.8'

services:
  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_URL=auth-server:3001
      - EVENT_SERVICE_URL=event-server:3002
    depends_on:
      - auth-server
      - event-server

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./auth-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/auth?authSource=admin
      - JWT_SECRET=your-secret-key
      - PORT=3001
    depends_on:
      - mongodb
    command: npm run start:dev

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./event-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/events?authSource=admin
      - JWT_SECRET=your-secret-key
      - PORT=3002
    depends_on:
      - mongodb
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  mongodb_data: 