version: '3.8'

services:
  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - AUTH_SERVICE_HOST=auth-server
      - AUTH_SERVICE_PORT=3001
      - EVENT_SERVICE_HOST=event-server
      - EVENT_SERVICE_PORT=3002
    depends_on:
      - auth-server
      - event-server
    networks:
      - app-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./auth-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/auth?authSource=admin
      - JWT_SECRET=your-secret-key
      - PORT=3001
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  event-server:
    build:
      context: ./event-server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./event-server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/events?authSource=admin
      - JWT_SECRET=your-secret-key
      - PORT=3002
    depends_on:
      - mongodb
    networks:
      - app-network
    command: npm run start:dev

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: 